### ISSUE TITLE
unsure why, but the program is failing out in execv()

### ISSUE THREAD

**Issue by hanetzer** [mgorny/eclean-kernel2#11]
Heyo, hoping you could help me out here, figure'd I'd file a bug report instead
of just annoying you on irc. As of right now eclean-kernel is unable to clean up
my old kernels, failing with the following errors.
```
proprietary-killer /usr/local/portage/personal # eclean-kernel 
* Removing kernel 4.14.0-gentoo (vmlinuz does not exist)
eclean-kernel has met the following issue:

  execv() arg 2 must contain only strings

If you believe that the mentioned issue is a bug, please report it
to https://bitbucket.org/mgorny/eclean-kernel/issues. If possible,
please attach the output of 'eclean-kernel --list-kernels' and your
regular eclean-kernel call with additional '--debug' argument.
proprietary-killer /usr/local/portage/personal # eclean-kernel  --debug
* Trying bootloader lilo
* Trying bootloader grub2
** /boot/grub/grub.cfg found
* In get_removal_list()
* Removing kernel 4.14.0-gentoo (vmlinuz does not exist)
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/eclean-kernel", line 26, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib64/python2.7/site-packages/ecleankernel/cli.py", line 209, in main
    k.real_kv, k.vmlinuz])
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
proprietary-killer /usr/local/portage/personal # eclean-kernel  --debug --list-kernels
4.14.3-gentoo [4.14.3-gentoo]:
- vmlinuz: /boot/vmlinuz-4.14.3-gentoo
- systemmap: /boot/System.map-4.14.3-gentoo
- config: /boot/config-4.14.3-gentoo
- initramfs: /boot/initramfs-4.14.3-gentoo.img
- modules: /lib64/modules/4.14.3-gentoo
- build: /usr/src/linux-4.14.3-gentoo
- last modified: 2017-12-01 22:45:24
4.14.1-gentoo [4.14.1-gentoo]:
- vmlinuz: /boot/vmlinuz-4.14.1-gentoo
- systemmap: /boot/System.map-4.14.1-gentoo
- config: /boot/config-4.14.1-gentoo
- initramfs: /boot/initramfs-4.14.1-gentoo.img
- modules: /lib64/modules/4.14.1-gentoo
- build: /usr/src/linux-4.14.1-gentoo
- last modified: 2017-11-22 13:51:24
4.14.0-gentoo [None]:
- modules: /lib64/modules/4.14.0-gentoo
- last modified: 2017-11-16 17:33:58
```

**Comment by mgorny** [comment]
1. This is the wrong bugtracker (you're not using ek2).
2. ek1 is no longer maintained. You're hitting one of the ultimately convoluted Python problems I don't have time to figure out. You can try a different Python version, that might help. Or a different locale. Or a different phase of the moon.
